# Generated by Django 6.0.2 on 2026-03-24 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Travels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('source', models.CharField(max_length=32)),
                ('destination', models.CharField(max_length=32)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('bus_type', models.CharField(max_length=32)),
                ('driver_number', models.BigIntegerField()),
                ('bus_number', models.CharField(max_length=10)),
                ('seats', models.PositiveIntegerField()),
            ],
        ),
    ]
